POST http://127.0.0.1:4000/login HTTP/1.1
content-type: application/json

{
    "email": "alejandro@mail.com",
    "password": "123456"
}

###

POST http://127.0.0.1:4000/register HTTP/1.1
content-type: application/json

{
    "id": "f056aadb-a264-4e44-bc71-6ef27bb30a55",
    "email": "alejandro@mail.com",
    "name": "Alejandro Ponce",
    "birthDate": "1995-07-24",
    "password": "123456"
}